version: '3.8'

services:
  web:
    build: .
    container_name: stripe-django-test
    ports:
      - "8000:8000"
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
      - .:/app
    environment:
      - DEBUG=True
      - SECRET_KEY=${SECRET_KEY}
      - STRIPE_PUBLIC_KEY=${STRIPE_PUBLIC_KEY}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - DATABASE_URL=sqlite:///db.sqlite3


